FROM ubuntu
RUN apt install zip
RUN touch test.txt
RUN echo "thankyou" > test.txt
RUN apt install tar
RUN touch test1.txt
RUN echo "welcome" > test1.txt
RUN mkdir example
RUN apt install git
RUN mv test.txt example
RUN mv test1.txt example
RUN tar -cvzf example.tar.gz example
CMD [ "ubuntu" ]

# FROM ubuntu
# WORKDIR /tmp
# RUN apt update && \
#     apt install -y zip tar git && \
#     echo "welcome" > test.txt && \
#     echo "thankyou" > test1.txt && \
#     mkdir example && \
#     mv test.txt example && \
#     mv test1.txt example && \
#     tar -cvf example.tar.gz example
